<?php


namespace Mastering\SampleModule\Model\ResourceModel\Item;


use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;
use Mastering\SampleModule\Model\Item;

class Collection extends AbstractCollection
{
    protected $_idFieldName = 'id';

    protected function _construct()
    {
        $this->_init(Item::class, \Mastering\SampleModule\Model\ResourceModel\Item::class);
        parent::_construct(); // TODO: Change the autogenerated stub
    }

}
