<?php


namespace UdemyMagento\FirstModule\Console\Command;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class CustomCommand extends Command
{
    public function configure()
    {
        $this->setName('training:helloworld')
            ->setDescription('the command prints out hello world')
            ->setAliases(['hw']);
        $this->setDefinition([
            new InputArgument('name',InputArgument::OPTIONAL,'the name of the person',
            null,null)
        ]);
        parent::configure(); // TODO: Change the autogenerated stub
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln('Hello World, '.$input->getArgument('name'));
    }
}
